services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./.database:/var/lib/postgresql/data
        ports:
            - 5432:5432